apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "designrepo.fullname" . }}-be-env
  labels:
    {{- include "designrepo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
