apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "designrepo.fullname" . }}-fe-env
  labels:
    {{- include "designrepo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
