apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "designrepo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.data | nindent 2 }}
