name: Build Container Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: designrepo-runners
    environment: HOMELAB
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.kagesenshi.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: backend
          push: false
          tags: designrepo-backend:latest
          cache-from: type=registry,ref=registry.kagesenshi.org/designrepo-backend:cache
          cache-to: type=registry,ref=registry.kagesenshi.org/designrepo-backend:cache,mode=max

  build-frontend:
    runs-on: designrepo-runners
    environment: HOMELAB
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.kagesenshi.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: frontend
          build-args: |
            BACKEND_URL=http://localhost:8000
          push: false
          tags: designrepo-frontend:latest
          cache-from: type=registry,ref=registry.kagesenshi.org/designrepo-frontend:cache
          cache-to: type=registry,ref=registry.kagesenshi.org/designrepo-frontend:cache,mode=max
